#---- Roles ----

roles = [
  { name: 'Basic', permission: 1 },
  { name: 'Elavated', permission: 2 },
  { name: 'Extra Elavated', permission: 3 },
  { name: 'Admin', permission: 4 },
  { name: 'Counsel Member', permission: 5 },
]

roles.each do |role|
  Role.find_or_create_by(name: role[:name]) do |r|
    r.permission = role[:permission]
  end
end


#---- Ranks ----

ranks = [
  { name: "Novice", threshold: 10, level: 1 },
  { name: "Apprentice", threshold: 100, level: 2 },
  { name: "Journeyman", threshold: 500, level: 3 },
  { name: "Adept", threshold: 1000, level: 4 },
  { name: "Expert", threshold: 2000, level: 5 },
  { name: "Master", threshold: 4000, level: 6 },
  { name: "Grandmaster", threshold: 6000, level: 7 },
  { name: "Legendary", threshold: 8000, level: 8 },
  { name: "Mythical", threshold: 9000, level: 9 },
  { name: "Godlike", threshold: 10000, level: 10 },
  { name: "Transcendent", threshold: -1, level: 11 }
]

ranks.each do |rank|
  Rank.find_or_create_by(name: rank[:name]) do |r|
    r.level = rank[:level]
    r.threshold = rank[:threshold]
  end
end

#---- Cateogies ----

categories = [
  { name: "Python" },
  { name: "Web Development" },
  { name: "Embedded" },
  { name: "C" },
  { name: "JavaScript" },
  { name: "Java" },
  { name: "Ruby" },
  { name: "PHP" },
  { name: "C++" },
  { name: "C#" },
  { name: "Swift" },
  { name: "Kotlin" },
  { name: "Go" },
  { name: "Rust" },
  { name: "TypeScript" },
  { name: "Perl" },
  { name: "Shell Scripting" },
  { name: "SQL" },
  { name: "NoSQL" },
  { name: "R" },
  { name: "MATLAB" },
  { name: "Haskell" },
  { name: "Scala" },
  { name: "Elixir" },
  { name: "Erlang" },
  { name: "Objective-C" },
  { name: "Dart" },
  { name: "F#" },
  { name: "Lisp" },
  { name: "Scheme" },
  { name: "Prolog" },
  { name: "Assembly" },
  { name: "Visual Basic" },
  { name: "Groovy" },
  { name: "Lua" },
  { name: "COBOL" },
  { name: "Fortran" },
  { name: "Ada" },
  { name: "Pascal" },
  { name: "SAS" },
  { name: "ColdFusion" },
  { name: "ABAP" },
  { name: "LabVIEW" },
  { name: "VBScript" },
  { name: "RPG" },
  { name: "OCaml" },
  { name: "Crystal" },
  { name: "Smalltalk" },
  { name: "AWK" },
  { name: "Tcl" },
  { name: "ActionScript" },
  { name: "Julia" },
  { name: "PowerShell" },
  { name: "Transact-SQL" },
  { name: "Bash" },
  { name: "Zsh" },
  { name: "Fish" },
  { name: "Regular Expressions" },
  { name: "CSS" },
  { name: "HTML" },
  { name: "XML" },
  { name: "JSON" },
  { name: "YAML" },
  { name: "TOML" },
  { name: "Markdown" },
  { name: "LaTeX" },
  { name: "Clojure" },
  { name: "Functional Programming" },
  { name: "Object-Oriented Programming" },
  { name: "Procedural Programming" },
  { name: "Event-Driven Programming" },
  { name: "Parallel Programming" },
  { name: "Aspect-Oriented Programming" },
  { name: "Logic Programming" },
  { name: "Declarative Programming" },
  { name: "Imperative Programming" },
  { name: "Generic Programming" },
  { name: "Reactive Programming" },
  { name: "Metaprogramming" },
  { name: "Test-Driven Development" },
  { name: "Behavior-Driven Development" },
  { name: "Agile Development" },
  { name: "Scrum" },
  { name: "Kanban" },
  { name: "Extreme Programming (XP)" },
  { name: "DevOps" },
  { name: "Continuous Integration" },
  { name: "Continuous Deployment" },
  { name: "Version Control" },
  { name: "Git" },
  { name: "SVN" },
  { name: "Mercurial" },
  { name: "CVS" },
  { name: "Database Design" },
  { name: "Data Modeling" },
  { name: "Big Data" },
  { name: "Machine Learning" },
  { name: "Artificial Intelligence" },
  { name: "Data Science" },
  { name: "Data Analysis" },
  { name: "Robotics" },
  { name: "IoT" },
  { name: "Cybersecurity" },
  { name: "Blockchain" },
  { name: "Cryptography" },
  { name: "Software Engineering" },
  { name: "Systems Programming" },
  { name: "Network Programming" },
  { name: "Game Development" },
  { name: "Mobile Development" },
  { name: "Desktop Development" },
  { name: "Cloud Computing" },
  { name: "Microservices" },
  { name: "API Development" },
  { name: "Web Services" },
  { name: "Serverless Architecture" },
  { name: "Containerization" },
  { name: "Virtualization" },
  { name: "Scripting Languages" },
  { name: "Markup Languages" },
  { name: "Configuration Languages" },
  { name: "Query Languages" },
  { name: "Domain-Specific Languages" },
  { name: "Embedded Systems" },
  { name: "Real-Time Systems" },
  { name: "Concurrency Control" },
  { name: "Memory Management" },
  { name: "Garbage Collection" },
  { name: "Operating Systems" },
  { name: "Compilers" },
  { name: "Interpreters" },
  { name: "Virtual Machines" },
  { name: "Middleware" },
  { name: "Network Security" },
  { name: "Penetration Testing" },
  { name: "Ethical Hacking" },
  { name: "Incident Response" },
  { name: "Digital Forensics" },
  { name: "Threat Modeling" },
  { name: "Security Auditing" },
  { name: "Cryptanalysis" },
  { name: "Formal Methods" },
  { name: "Program Verification" },
  { name: "Static Analysis" },
  { name: "Dynamic Analysis" },
  { name: "Performance Optimization" },
  { name: "Parallel Algorithms" },
  { name: "Distributed Algorithms" },
  { name: "Approximation Algorithms" },
  { name: "Randomized Algorithms" },
  { name: "Quantum Computing" },
  { name: "Numerical Methods" },
  { name: "High Performance Computing" },
  { name: "Graph Theory" },
  { name: "Combinatorics" },
  { name: "Discrete Mathematics" },
  { name: "Automata Theory" },
  { name: "Computability Theory" },
  { name: "Information Theory" },
  { name: "Algorithm Analysis" },
  { name: "Data Structures" },
  { name: "Graph Algorithms" },
  { name: "Sorting Algorithms" },
  { name: "Search Algorithms" },
  { name: "Optimization Algorithms" },
  { name: "Machine Learning Algorithms" },
  { name: "Data Mining" },
  { name: "Recommender Systems" },
  { name: "Pattern Recognition" },
  { name: "Predictive Analytics" },
  { name: "Time Series Analysis" },
  { name: "Anomaly Detection" },
  { name: "Feature Engineering" },
  { name: "Model Selection" },
  { name: "Hyperparameter Tuning" },
  { name: "Deep Learning" },
  { name: "Neural Networks" },
  { name: "Convolutional Neural Networks" },
  { name: "Recurrent Neural Networks" },
  { name: "Generative Adversarial Networks" },
  { name: "Transfer Learning" },
  { name: "Reinforcement Learning" },
  { name: "Natural Language Understanding" },
  { name: "Speech Recognition" },
  { name: "Image Processing" },
  { name: "3D Graphics" },
  { name: "Virtual Reality" },
  { name: "Augmented Reality" },
  { name: "Game Design" },
  { name: "Game Physics" },
  { name: "Animation" },
  { name: "User Interface Design" },
  { name: "User Experience Design" },
  { name: "Accessibility" },
  { name: "Human-Computer Interaction" },
  { name: "Mobile App Design" },
  { name: "Responsive Design" },
  { name: "Backend Development" },
  { name: "Frontend Development" },
  { name: "Full Stack Development" },
  { name: "Progressive Web Apps" },
  { name: "Single Page Applications" },
  { name: "Micro Frontends" },
  { name: "SEO" },
  { name: "Content Management Systems" },
  { name: "E-commerce" },
  { name: "Web Performance Optimization" },
  { name: "Cloud Architecture" },
  { name: "Cloud Security" },
  { name: "Cloud Migration" },
  { name: "Cloud Management" },
  { name: "Cloud Monitoring" },
  { name: "Cloud Networking" },
  { name: "Cloud Storage" },
  { name: "Cloud Services" },
  { name: "Cloud Automation" },
  { name: "Cloud Governance" },
  { name: "IoT Development" },
  { name: "IoT Platforms" },
  { name: "IoT Security" },
  { name: "IoT Connectivity" },
  { name: "IoT Analytics" },
  { name: "IoT Sensors" },
  { name: "IoT Actuators" },
  { name: "IoT Protocols" },
  { name: "IoT Edge Computing" },
  { name: "Blockchain Development" },
  { name: "Smart Contracts" },
  { name: "Decentralized Applications" },
  { name: "Blockchain Security" },
  { name: "Blockchain Governance" },
  { name: "Blockchain Interoperability" },
  { name: "Blockchain Scalability" },
  { name: "Blockchain Consensus Mechanisms" },
  { name: "Blockchain Privacy" },
  { name: "Blockchain Regulation" },
  { name: "Quantum Cryptography" },
  { name: "Post-Quantum Cryptography" },
  { name: "Homomorphic Encryption" },
  { name: "Zero-Knowledge Proofs" },
  { name: "Secure Multiparty Computation" },
  { name: "Lattice-based Cryptography" },
  { name: "Quantum Key Distribution" },
  { name: "Quantum Secure Direct Communication" },
  { name: "Quantum Cryptanalysis" },
  { name: "Quantum-resistant Cryptography" },
  { name: "Federated Learning" },
  { name: "Differential Privacy" },
  { name: "Privacy-Enhancing Technologies" },
  { name: "Secure Multi-Party Computation" },
  { name: "Privacy-preserving Data Mining" },
  { name: "Anonymization Techniques" },
  { name: "Data Protection Regulations" },
  { name: "Ethical AI" },
  { name: "Edge Computing" },
  { name: "Fog Computing" },
  { name: "Multi-Cloud Computing" },
  { name: "Hybrid Cloud Computing" },
  { name: "Cloud-Native Development" },
  { name: "Cloud Orchestration" },
  { name: "Cloud Cost Management" },
  { name: "Function as a Service (FaaS)" },
  { name: "Backend as a Service (BaaS)" },
  { name: "Frontend as a Service (FaaS)" },
  { name: "Database as a Service (DBaaS)" },
  { name: "Identity as a Service (IDaaS)" },
  { name: "Security as a Service (SECaaS)" },
  { name: "Networking as a Service (NaaS)" },
  { name: "Data as a Service (DaaS)" },
  { name: "Containers" },
  { name: "Container Orchestration" },
  { name: "Container Management" },
  { name: "Kubernetes" },
  { name: "Docker" },
  { name: "Mesos" },
  { name: "Service Mesh" },
  { name: "API Gateway" },
  { name: "API Management" },
  { name: "API Security" },
  { name: "RESTful APIs" },
  { name: "GraphQL APIs" },
  { name: "SOAP APIs" },
  { name: "WebSockets" },
  { name: "Event-Driven Architecture" },
  { name: "Message Queue" },
  { name: "Message Broker" },
  { name: "Event Bus" },
  { name: "Pub/Sub" },
  { name: "Stream Processing" },
  { name: "Complex Event Processing (CEP)" },
  { name: "Event Sourcing" },
  { name: "CQRS (Command Query Responsibility Segregation)" },
  { name: "Saga Pattern" },
  { name: "Server-Side Rendering (SSR)" },
  { name: "Client-Side Rendering (CSR)" },
  { name: "Static Site Generation (SSG)" },
  { name: "Jamstack" },
  { name: "Progressive Web Apps (PWA)" },
  { name: "Single Page Applications (SPA)" },
  { name: "Dynamic Web Applications" },
  { name: "Cross-Platform Development" },
  { name: "Native Mobile Development" },
  { name: "Hybrid Mobile Development" },
  { name: "Mobile App Frameworks" },
  { name: "Mobile UI Frameworks" },
  { name: "Native Desktop Development" },
  { name: "Cross-Platform Desktop Development" },
  { name: "Desktop UI Frameworks" },
  { name: "Game Engines" },
  { name: "Game Frameworks" },
  { name: "Game Development Platforms" },
  { name: "Game Design Patterns" },
  { name: "Game Networking" },
  { name: "Game AI" },
  { name: "Game Audio" },
  { name: "Game Testing" },
  { name: "Game Monetization" },
  { name: "Data Compression" },
  { name: "Error Detection and Correction" },
  { name: "Network Protocols" },
  { name: "Socket Programming" },
  { name: "Concurrent Programming" },
  { name: "Distributed Systems" },
  { name: "Fault Tolerance" },
  { name: "Cluster Computing" },
  { name: "Grid Computing" },
  { name: "High-Performance Computing" },
  { name: "Scientific Computing" },
  { name: "Numerical Analysis" },
  { name: "Computational Physics" },
  { name: "Computational Chemistry" },
  { name: "Computational Biology" },
  { name: "Computational Neuroscience" },
  { name: "Computational Linguistics" },
  { name: "Geospatial Analysis" },
  { name: "Signal Processing" },
  { name: "Image Analysis" },
  { name: "Text Analysis" },
  { name: "Audio Analysis" },
  { name: "Video Analysis" },
  { name: "Biometric Analysis" },
  { name: "Geometric Modeling" },
  { name: "Solid Modeling" },
  { name: "Computer Vision" },
  { name: "Natural Language Processing" },
  { name: "Speech Processing" },
  { name: "Knowledge Representation" },
  { name: "Semantic Web" },
  { name: "Information Retrieval" },
  { name: "Information Extraction" },
  { name: "Question Answering Systems" },
  { name: "Expert Systems" },
  { name: "Knowledge Engineering" },
  { name: "Autonomous Systems" },
  { name: "Industrial Automation" },
  { name: "Humanoid Robotics" },
  { name: "Medical Robotics" },
  { name: "Bioinformatics" },
  { name: "Health Informatics" },
  { name: "Clinical Informatics" },
  { name: "Imaging Informatics" },
  { name: "Public Health Informatics" },
  { name: "Consumer Health Informatics" },
  { name: "Molecular Modeling" },
  { name: "Drug Design" },
  { name: "Pharmacoinformatics" },
  { name: "Chemoinformatics" },
  { name: "Genomics" },
  { name: "Proteomics" },
  { name: "Metabolomics" },
  { name: "Systems Biology" },
  { name: "Biomedical Imaging" },
  { name: "Medical Diagnostics" },
  { name: "Digital Pathology" },
  { name: "Telemedicine" },
  { name: "Health Monitoring Systems" },
  { name: "Remote Patient Monitoring" },
  { name: "Hospital Information Systems" },
  { name: "Electronic Health Records" },
  { name: "Healthcare Data Analytics" },
  { name: "Clinical Decision Support Systems" },
  { name: "Health Information Exchange" },
  { name: "Medical Billing Systems" },
  { name: "Practice Management Systems" },
  { name: "Healthcare Supply Chain Management" },
  { name: "Pharmacy Management Systems" },
  { name: "Radiology Information Systems" },
  { name: "Laboratory Information Systems" },
  { name: "Genetic Counseling Systems" },
  { name: "Remote Sensing" },
  { name: "Geographic Information Systems" },
  { name: "Geospatial Technology" },
  { name: "Vue.js" },
  { name: "React.js" },
  { name: "Angular" },
  { name: "Ember.js" },
  { name: "Backbone.js" },
  { name: "Django" },
  { name: "Flask" },
  { name: "PyTorch" },
  { name: "TensorFlow" },
  { name: "Keras" },
  { name: "Ruby on Rails" },
  { name: "Sinatra" },
  { name: "Express.js" },
  { name: "Next.js" },
  { name: "Nuxt.js" },
  { name: "Svelte" },
  { name: "Spring Framework" },
  { name: "Hibernate" },
  { name: "Struts" },
  { name: "Play Framework" },
  { name: "Laravel" },
  { name: "Symfony" },
  { name: "CodeIgniter" },
  { name: "Zend Framework" },
  { name: "ASP.NET" },
  { name: "ASP.NET Core" },
  { name: "MVC Framework" },
  { name: "Hanami" },
  { name: "Padrino" },
  { name: "Grails" },
  { name: "Micronaut" },
  { name: "Quarkus" },
  { name: "Vert.x" },
  { name: "Meteor" },
  { name: "AdonisJS" },
  { name: "NestJS" },
  { name: "Phoenix Framework" },
  { name: "Rocket" },
  { name: "Actix" },
  { name: "ActFramework" },
  { name: "CakePHP" },
  { name: "FuelPHP" },
  { name: "Phalcon" },
  { name: "Yii" },
  { name: "Lumen" },
  { name: "Slim" },
  { name: "Ninja Framework" },
  { name: "Ratpack" },
  { name: "Dropwizard" },
  { name: "Gin" },
  { name: "Beego" },
  { name: "Echo" },
  { name: "NancyFX" },
  { name: "ServiceStack" },
  { name: "Spring Boot" },
  { name: "Vaadin" },
  { name: "GWT (Google Web Toolkit)" },
  { name: "JSF (JavaServer Faces)" },
  { name: "Wicket" },
  { name: "Tapestry" },
  { name: "Blazor" },
  { name: "Django REST framework" },
  { name: "FastAPI" },
  { name: "Sanic" },
  { name: "Gin-Gonic" },
  { name: "Koa" },
  { name: "Hapi" },
  { name: "Sails.js" },
  { name: "LoopBack" },
  { name: "Feathers" },
  { name: "Strapi" },
  { name: "Gatsby" },
  { name: "Sapper" },
  { name: "Create React App" },
  { name: "Angular CLI" },
  { name: "Vue CLI" },
  { name: "Quasar" },
  { name: "Gridsome" },
  { name: "SvelteKit" },
  { name: "Moleculer" },
  { name: "KeystoneJS" },
  { name: "GraphCMS" },
  { name: "Sanity" },
  { name: "Directus" },
  { name: "Bottle" },
  { name: "CherryPy" },
  { name: "TurboGears" },
  { name: "Pyramid" },
  { name: "Web2py" },
  { name: "Falcon" },
  { name: "Starlette" },
  { name: "Tornado" },
  { name: "Quart" },
  { name: "Cuba" },
  { name: "Volt" },
  { name: "Lucky" },
  { name: "Plone" },
  { name: "Zope" },
  { name: "Hugo" }
]




categories.each do |category|
  Category.find_or_create_by(name: category[:name]) do |c|
    c.name = category[:name]
  end
end



#---- Users ----

users = [
  { email: 'root@root.com', username: 'Administrator', password: '12345678', password_confirmation: '12345678', rank: Rank.find_by(level: 11), xp: 1000, role: Role.find_by(name: "Counsel Member") },
]

users.each do |user|
  User.find_or_create_by(email: user[:email]) do |u|
    u.username = user[:username]
    u.password = user[:password]
    u.password_confirmation = user[:password_confirmation]
    u.rank = user[:rank]
    u.xp = user[:xp]
    u.role = user[:role]
  end
end


#----- random data

chargen = [
  -> { Faker::Movies::BackToTheFuture.character },
  -> { Faker::Movies::HarryPotter.character },
  -> { Faker::Movies::Hobbit.character },
  -> { Faker::Movies::HowToTrainYourDragon.character },
  -> { Faker::Movies::LordOfTheRings.character },
  -> { Faker::Movies::StarWars.character },
  -> { Faker::Movies::VForVendetta.character },
  -> { Faker::TvShows::BreakingBad.character },
  -> { Faker::TvShows::Spongebob.character },
  -> { Faker::TvShows::Simpsons.character }

]

textgen = [
  -> {  Faker::TvShows::FamilyGuy.quote },
  -> {  Faker::TvShows::RickAndMorty.quote },
  -> {  Faker::TvShows::Spongebob.quote },
  -> {  Faker::TvShows::SouthPark.quote },
  -> {  Faker::TvShows::Simpsons.quote },
  -> {  Faker::Quote.famous_last_words },
  -> {  Faker::Quote.yoda },
  -> {  Faker::Movie.quote },
  -> {  Faker::Movies::Hobbit.quote },
  -> {  Faker::Movies::StarWars.quote },
  -> {  Faker::Movies::VForVendetta.speech },
  -> {  Faker::Movies::VForVendetta.quote },
]

headgen = [
  -> {  Faker::TvShows::FamilyGuy.quote },
  -> {  Faker::TvShows::RickAndMorty.quote },
  -> {  Faker::TvShows::Spongebob.quote },
  -> {  Faker::TvShows::SouthPark.quote },
  -> {  Faker::TvShows::Simpsons.quote },
  -> {  Faker::Quote.famous_last_words },
  -> {  Faker::Quote.yoda },
  -> {  Faker::Movie.quote },
  -> {  Faker::Movies::Hobbit.quote },
  -> {  Faker::Movies::StarWars.quote },
  -> {  Faker::Movies::VForVendetta.quote },
]

chargen.each do |generator|
  2.times do
    User.create(
      {
        username: generator.call,
        email: "#{Faker::Name.first_name}@#{Faker::Name.last_name}.com",
        password: '12345678',
        password_confirmation: '12345678',
        rank: Rank.find_by(level: 1),
        xp: 0,
        role: Role.find_by(name: 'Basic')
      }
    )
  end
end

textgen.each do |generator|
  5.times do
    user = User.order('RANDOM()').first
    user.update(xp: user.xp + 50)

    h = ''
    h = headgen.sample.call while h.length > 75 || h.empty?

    Question.new(
      {
        heading: h,
        text: generator.call,
        user: user
      }
    ).save
  end
end
